// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutTextSplit from '@/components/sections/about/AboutTextSplit';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutTextSplit
          title="Built for Success"
          descriptions={[
            "Summit Digital transforms your business ideas into high-converting digital realities. We specialize in bespoke, performance-driven web solutions designed to scale your reach and streamline your operations.",
            "Our philosophy is rooted in technical excellence and user-centered design, ensuring your site is not just beautiful, but a true catalyst for your brand's growth.",
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
