// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
        tag="Launch"
        text="Ready to build your masterpiece?"
        primaryButton={{"text":"Schedule Consultation","href":"mailto:hectorbarber920@gmail.com"}}
        secondaryButton={{
            text: "View Portfolio",
            href: "#features",
          }}
        textAnimation="fade-blur"
      />
        </SectionErrorBoundary>
      </div>
  );
}
