// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqSimple from '@/components/sections/faq/FaqSimple';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqSimple
          tag="Help"
          title="Common Questions"
          description="Answers to help you get started with Summit Digital."
          items={[
            {
              question: "What is the timeline for a website?",
              answer: "Most projects are completed within 4-6 weeks depending on complexity.",
            },
            {
              question: "Do you offer maintenance?",
              answer: "Yes, we provide ongoing maintenance and performance monitoring services.",
            },
            {
              question: "How do payments work?",
              answer: "Payment is collected only after the website is finished.",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
