// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "features" section.

import React from 'react';
import FeaturesMediaCards from '@/components/sections/features/FeaturesMediaCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FeaturesSection(): React.JSX.Element {
  return (
    <div id="features" data-section="features">
        <SectionErrorBoundary name="features">
              <FeaturesMediaCards
          tag="Our Services"
          title="End-to-End Solutions"
          description="Comprehensive development services tailored to your specific business requirements."
          items={[
            {
              title: "Performance Optimization",
              description: "Blazing fast load times and clean code for better SEO and user satisfaction.",
              imageSrc: "http://img.b2bpic.net/free-photo/internet-speed-test-software-concept_53876-120681.jpg",
            },
            {
              title: "SEO & Strategy",
              description: "Advanced search engine optimization to ensure your site is found by the right audience.",
              imageSrc: "http://img.b2bpic.net/free-photo/technology-hologram-indoors_23-2151833347.jpg",
            },
            {
              title: "Responsive Design",
              description: "Flawless mobile, tablet, and desktop experience to keep your customers engaged.",
              imageSrc: "http://img.b2bpic.net/free-photo/high-angle-tablet-desk-with-copy-space_23-2148697018.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
