// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroBrand from '@/components/sections/hero/HeroBrand';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroBrand
          brand="Summit Digital"
          description="Elevate your online presence with professional, high-performance website design built for growth and impact."
          primaryButton={{
            text: "Get Started",
            href: "#contact",
          }}
          secondaryButton={{
            text: "Learn More",
            href: "#about",
          }}
          imageSrc="http://img.b2bpic.net/free-photo/still-life-graphic-design-office_23-2151345405.jpg"
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
