// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsFeatureCards from '@/components/sections/metrics/MetricsFeatureCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsFeatureCards
          tag="Performance"
          title="Quantifiable Growth"
          description="We don't just build sites; we build performance engines."
          metrics={[
            {
              value: "2x",
              title: "Avg Conversion Lift",
              features: [
                "Speed optimized",
                "SEO refined",
              ],
            },
            {
              value: "98/100",
              title: "Avg PageSpeed Score",
              features: [
                "Perfectly optimized",
                "Clean architecture",
              ],
            },
            {
              value: "40%",
              title: "Avg Traffic Increase",
              features: [
                "SEO best practices",
                "Modern tech stack",
              ],
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
