// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialOverlayCards from '@/components/sections/testimonial/TestimonialOverlayCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialOverlayCards
          tag="Clients"
          title="Trusted by Leaders"
          description="See why businesses trust Summit Digital for their online growth."
          testimonials={[
            {
              name: "Alex Rivet",
              role: "CEO",
              company: "TechInnovate",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/project-manager-sitting-office-desk_482257-127147.jpg",
            },
            {
              name: "Sarah Chen",
              role: "Founder",
              company: "GrowthLab",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/businessman-using-mobile-phone_107420-84909.jpg",
            },
            {
              name: "Mark D.",
              role: "CMO",
              company: "MarketFlow",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/spectacular-african-man-with-sincere-smile-posing-outdoor-photo-cute-black-male-model-glasses-headphones_197531-21894.jpg",
            },
            {
              name: "Elena V.",
              role: "Director",
              company: "StyleStudio",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-successful-businesswoman-with-charming-smile-posing-street-with-interesting-architecture-background_613910-14028.jpg",
            },
            {
              name: "James K.",
              role: "Owner",
              company: "SummitGear",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-happy-businessman-with-crossed-arms_23-2147955274.jpg",
            },
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
